apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yandex-messenger-bridge.fullname" . }}
  labels:
    {{- include "yandex-messenger-bridge.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc | quote }}
